version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
            links:
                - db
              depends_on:
                - db
              restart: on-failure
    db:
        image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=cursor
      - POSTGRES_PASSWORD=very_secret_password
      - POSTGRES_DB=cursor_sqlalchemy_db
    ports:
      - 5432:5432